### ISSUE TITLE
Something again in repo/notebook that shouldn't be

### ISSUE THREAD

**Issue by R4ZZ3** [TurkuNLP/LLM_document_descriptors#1]
Check your [https://github.com/TurkuNLP/ocr-postcorrection-lm/blob/main/alignment-and-gridsearch/alignment_test.ipynb file](https://github.com/TurkuNLP/LLM_document_descriptors/blob/main/notebooks/Untitled1.ipynb)

There is something visible in there which probably shouldn't be.

**Comment by OttoTarkka** [comment]
Thanks for pointing this out! I have now invalidated this key.
